name: Non-docs workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # The job that determines, based on which files were changed, whether the
  # "main job" should run.
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      main_job_should_run: ${{ steps.changed-files.outputs.should_run }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Determine if non-docs files changed
        id: changed-files
        run: |
          # Get the list of changed files between the last two commits
          changed_files=$(git diff --name-only HEAD~1 HEAD)

          # Exclude files with the "docs/" prefix. The " || true" at the end is
          # needed because grep is being used outside of an if statement and we
          # need the script to continue even if grep returns a non-0 exit code,
          # which it does when there is no match.
          non_docs_files=$(echo "$changed_files" | grep -v '^docs/' || true)

          # Check if any non-docs files exist
          if [ -n "$non_docs_files" ]; then
            echo "Code files (non-docs) changed."
            echo "code_files_changed=true" >> $GITHUB_OUTPUT
          fi

  # The main job of the workflow. Should only run if the files related to the
  # workflow were modified.
  non-docs-stuff:
    runs-on: ubuntu-latest
    needs: changed-files
    if: ${{ needs.changed-files.outputs.main_job_should_run }}
    steps:
      - run: 'echo "the non-docs main job is running"'
