name: Docs workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # The job that determines, based on which files were changed, whether the
  # "main job" should run.
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      main_job_should_run: ${{ steps.set-output.outputs.should_run }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Tmp
        run: |
          git log

      - name: Determine if docs files changed
        id: check-docs
        run: |
          # Get the list of changed files between the last two commits
          changed_files=$(git diff --name-only HEAD~1 HEAD)

          # Check if any of the changed files are in the "docs/" directory
          if echo "$changed_files" | grep -q '^docs/'; then
            echo "Docs files changed."
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "No docs files changed."
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  # The main job of the workflow. Should only run if the files related to the
  # workflow were modified.
  docs-stuff:
    runs-on: ubuntu-latest
    needs: changed-files
    if: ${{ needs.changed-files.outputs.main_job_should_run }}
    steps:
      - run: 'echo "the docs main job is running"'
